---
title: "Contribution Statements"
subtitle: "COVID-19 Vaccination in Germany — StatProg2 Group Project"
format:
  pdf:
    papersize: a4
    geometry:
      - margin=2.5cm
    fontsize: 11pt
    colorlinks: true
---

## Felix Obermaier — Contribution Statement

**Primarily responsible for:** project website, RQ1 analysis and results

-   *Building the Quarto website from scratch*
-   *Continuously update the project website while analysis progress was made*
-   *RQ1, presenting visualizations and results on the project website*

**Collaborative tasks:** Together, we defined and refined the research questions and overall analysis plan. We jointly discussed methodological decisions, reviewed each other’s code, plots and interpretations, and improved the analyses based on mutual feedback. We also worked together on the proposal, README, group reflection, final project structure and the preparation of the final submission.

## Lukas Seibold — Contribution Statement

**Primarily responsible for:** complete Analysis RQ2 (a and b), preliminary RQ1 analysis

-   *Initial Data Analysis (IDA) for the proposal*
-   *improving plots (Week 11, Practical 10)*
-   *`{infer}` Analysis, RQ2*

**Collaborative tasks:** Together, we defined and refined the research questions and overall analysis plan. We jointly discussed methodological decisions, reviewed each other’s code, plots and interpretations, and improved the analyses based on mutual feedback. We also worked together on the proposal, README, group reflection, final project structure and the preparation of the final submission.
