<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>proposal_website – StatProg2_project - COVID-19 Vaccination in Germany</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">StatProg2_project - COVID-19 Vaccination in Germany</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./proposal_website.html" aria-current="page"> 
<span class="menu-text">Project Proposal</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./dataset_website.html"> 
<span class="menu-text">Dataset</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./analysis_website.html"> 
<span class="menu-text">Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./results_website.html"> 
<span class="menu-text">Results</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link active" data-scroll-target="#research-questions">Research Questions</a>
  <ul class="collapse">
  <li><a href="#question-1-how-did-vaccination-coverage-in-germany-develop-during-the-covid-19-pandemic" id="toc-question-1-how-did-vaccination-coverage-in-germany-develop-during-the-covid-19-pandemic" class="nav-link" data-scroll-target="#question-1-how-did-vaccination-coverage-in-germany-develop-during-the-covid-19-pandemic">Question 1: How did vaccination coverage in Germany develop during the COVID-19 pandemic?</a></li>
  <li><a href="#question-2-how-did-vaccination-coverage-relate-to-different-dimensions-of-covid-19-severity-in-germany" id="toc-question-2-how-did-vaccination-coverage-relate-to-different-dimensions-of-covid-19-severity-in-germany" class="nav-link" data-scroll-target="#question-2-how-did-vaccination-coverage-relate-to-different-dimensions-of-covid-19-severity-in-germany">Question 2: How did vaccination coverage relate to different dimensions of COVID-19 severity in Germany?</a></li>
  <li><a href="#sub-question-2a-are-higher-vaccination-rates-associated-with-lower-covid-19-mortality" id="toc-sub-question-2a-are-higher-vaccination-rates-associated-with-lower-covid-19-mortality" class="nav-link" data-scroll-target="#sub-question-2a-are-higher-vaccination-rates-associated-with-lower-covid-19-mortality">Sub-question 2a: Are higher vaccination rates associated with lower COVID-19 mortality?</a></li>
  <li><a href="#sub-question-2b-are-higher-vaccination-rates-associated-with-lower-icu-occupancy" id="toc-sub-question-2b-are-higher-vaccination-rates-associated-with-lower-icu-occupancy" class="nav-link" data-scroll-target="#sub-question-2b-are-higher-vaccination-rates-associated-with-lower-icu-occupancy">Sub-question 2b: Are higher vaccination rates associated with lower ICU occupancy?</a></li>
  </ul></li>
  <li><a href="#audience-and-context" id="toc-audience-and-context" class="nav-link" data-scroll-target="#audience-and-context">Audience and Context</a></li>
  <li><a href="#domain-informed-quality-checks" id="toc-domain-informed-quality-checks" class="nav-link" data-scroll-target="#domain-informed-quality-checks">Domain-informed quality checks</a></li>
  <li><a href="#initial-data-analysis-ida" id="toc-initial-data-analysis-ida" class="nav-link" data-scroll-target="#initial-data-analysis-ida">Initial Data Analysis (IDA)</a></li>
  <li><a href="#analysis-plan" id="toc-analysis-plan" class="nav-link" data-scroll-target="#analysis-plan"><strong>Analysis plan</strong></a></li>
  <li><a href="#workflow-organisation" id="toc-workflow-organisation" class="nav-link" data-scroll-target="#workflow-organisation">Workflow organisation</a></li>
  <li><a href="#answering-the-research-questions" id="toc-answering-the-research-questions" class="nav-link" data-scroll-target="#answering-the-research-questions">Answering the Research Questions</a>
  <ul class="collapse">
  <li><a href="#research-question-1" id="toc-research-question-1" class="nav-link" data-scroll-target="#research-question-1">Research Question 1</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="research-questions" class="level2">
<h2 class="anchored" data-anchor-id="research-questions">Research Questions</h2>
<section id="question-1-how-did-vaccination-coverage-in-germany-develop-during-the-covid-19-pandemic" class="level3">
<h3 class="anchored" data-anchor-id="question-1-how-did-vaccination-coverage-in-germany-develop-during-the-covid-19-pandemic">Question 1: How did vaccination coverage in Germany develop during the COVID-19 pandemic?</h3>
<p>We will analyse <code>people_fully_vaccinated_per_hundred</code> together with <code>new_vaccinations_smoothed</code> and <code>date</code>, to analyse the development of COVID-19 vaccination coverage in Germany. Using line plots and descriptive statistics, we will identify the start of the vaccination campaign, periods of rapid vaccine uptake, peak vaccination activity, and the later plateau in vaccination coverage.</p>
<p><strong>Goal:</strong> Descriptive</p>
<p><strong>Type:</strong> Confirmatory</p>
<hr>
</section>
<section id="question-2-how-did-vaccination-coverage-relate-to-different-dimensions-of-covid-19-severity-in-germany" class="level3">
<h3 class="anchored" data-anchor-id="question-2-how-did-vaccination-coverage-relate-to-different-dimensions-of-covid-19-severity-in-germany">Question 2: How did vaccination coverage relate to different dimensions of COVID-19 severity in Germany?</h3>
<p>We investigate whether COVID-19 vaccination coverage was associated with different dimensions of disease severity in Germany. To explore these relationships, we focus separately on mortality and ICU occupancy without making causal claims about the effects of vaccination.</p>
<p><strong>Goal:</strong> Exploratory</p>
<p><strong>Type:</strong> Exploratory</p>
</section>
<section id="sub-question-2a-are-higher-vaccination-rates-associated-with-lower-covid-19-mortality" class="level3">
<h3 class="anchored" data-anchor-id="sub-question-2a-are-higher-vaccination-rates-associated-with-lower-covid-19-mortality">Sub-question 2a: Are higher vaccination rates associated with lower COVID-19 mortality?</h3>
<p>We will analyse <code>people_vaccinated_per_hundred</code> together with <code>new_deaths_smoothed</code> and <code>date</code> using line plots, scatter plots, correlation analysis, and descriptive statistics to examine whether higher vaccination coverage was associated with lower COVID-19 mortality in Germany.</p>
<p>Since this is an exploratory analysis, we investigate associations between vaccination coverage and mortality without making strong causal claims.</p>
</section>
<section id="sub-question-2b-are-higher-vaccination-rates-associated-with-lower-icu-occupancy" class="level3">
<h3 class="anchored" data-anchor-id="sub-question-2b-are-higher-vaccination-rates-associated-with-lower-icu-occupancy">Sub-question 2b: Are higher vaccination rates associated with lower ICU occupancy?</h3>
<p>We will analyse <code>people_vaccinated_per_hundred</code> together with <code>icu_patients</code> and <code>date</code> using line plots, scatter plots, correlation analysis, and descriptive statistics to examine whether higher vaccination coverage was associated with lower ICU occupancy in Germany.</p>
<p>Since this is an exploratory analysis, we investigate associations between vaccination coverage and ICU occupancy without making strong causal claims.</p>
<hr>
</section>
</section>
<section id="audience-and-context" class="level2">
<h2 class="anchored" data-anchor-id="audience-and-context">Audience and Context</h2>
<p>This analysis is conducted in an academic setting as part of a data science and statistical programming project. The goal is to explore COVID-19 vaccination trends in Germany and investigate possible relationships between vaccination coverage, mortality, and intensive care unit (ICU) occupancy.</p>
<p>The primary audience consists of students, instructors, and individuals interested in understanding the development of vaccination campaigns during the COVID-19 pandemic. The analysis aims to communicate findings in a clear, accessible, and data-driven manner.</p>
<p>The results will be presented through a GitHub-hosted website created with Quarto. Appropriate presentation formats include interactive and static visualizations, time-series plots, scatter plots, statistical summaries, and brief written interpretations. This format allows the audience to explore the results and understand the key findings through both text and graphics.</p>
</section>
<section id="domain-informed-quality-checks" class="level2">
<h2 class="anchored" data-anchor-id="domain-informed-quality-checks">Domain-informed quality checks</h2>
<p>We examined the key variables used in our analysis.</p>
<ul>
<li>Vaccination rates (<code>people_vaccinated_per_hundred</code> and <code>people_fully_vaccinated_per_hundred</code>) range from 0 to approximately 78 percent, which is within plausible bounds.</li>
<li>ICU patient counts range from 100 to 5761 and contain no negative values.</li>
<li>Daily death counts are non-negative, although some unusually large values appear and may reflect reporting corrections or delayed reporting.</li>
<li>Several variables contain missing values. Vaccination variables have more than 800 missing observations, while ICU patient counts and death counts also contain missing data. These missing values are likely related to changes in reporting availability over time. Some variables are completely missing for Germany and will therefore not be used in the analysis.</li>
</ul>
</section>
<section id="initial-data-analysis-ida" class="level2">
<h2 class="anchored" data-anchor-id="initial-data-analysis-ida">Initial Data Analysis (IDA)</h2>
<section id="structure-of-the-data" class="level4">
<h4 class="anchored" data-anchor-id="structure-of-the-data">Structure of the data</h4>
<p>We use <code>glimpse()</code> to confirm the dimensions and data types of our key variables.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>covid_germany <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    date, total_cases, new_cases, new_cases_smoothed,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    total_deaths, new_deaths, new_deaths_smoothed,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    reproduction_rate, icu_patients, hosp_patients,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    people_vaccinated_per_hundred, people_fully_vaccinated_per_hundred,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    stringency_index</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">glimpse</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The structure matches our expectations: <code>date</code> is read as a proper <code>date</code> type and all measurement and count variables are numeric. Cumulative variables (<code>total_cases</code>, <code>total_deaths</code>) are present from the start, while smoothed, reproduction, ICU, and vaccination variables only begin later in the pandemic, which is reflected in the leading <code>NA</code> values.</p>
</section>
<section id="summary-statistics-for-key-variables" class="level4">
<h4 class="anchored" data-anchor-id="summary-statistics-for-key-variables">Summary statistics for key variables</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>covid_germany <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    new_cases, new_cases_smoothed, new_deaths, new_deaths_smoothed,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    reproduction_rate, icu_patients,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    people_vaccinated_per_hundred, people_fully_vaccinated_per_hundred,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    stringency_index</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The table below reports the main summary statistics together with the number of missing values per variable.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Min</th>
<th>Median</th>
<th>Mean</th>
<th>Max</th>
<th>NA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>new_cases</code></td>
<td>0</td>
<td>0</td>
<td>29,983</td>
<td>1,588,891</td>
<td>392</td>
</tr>
<tr class="even">
<td><code>new_cases_smoothed</code></td>
<td>0</td>
<td>11,167</td>
<td>30,100</td>
<td>226,984</td>
<td>397</td>
</tr>
<tr class="odd">
<td><code>new_deaths</code></td>
<td>0</td>
<td>0</td>
<td>136.5</td>
<td>6,460</td>
<td>392</td>
</tr>
<tr class="even">
<td><code>new_deaths_smoothed</code></td>
<td>0</td>
<td>79.0</td>
<td>137.0</td>
<td>922.9</td>
<td>397</td>
</tr>
<tr class="odd">
<td><code>reproduction_rate</code></td>
<td>0.52</td>
<td>1.07</td>
<td>1.10</td>
<td>3.00</td>
<td>637</td>
</tr>
<tr class="even">
<td><code>icu_patients</code></td>
<td>100</td>
<td>1,253</td>
<td>1,771</td>
<td>5,761</td>
<td>480</td>
</tr>
<tr class="odd">
<td><code>people_vaccinated_per_hundred</code></td>
<td>0.03</td>
<td>77.1</td>
<td>62.5</td>
<td>77.8</td>
<td>842</td>
</tr>
<tr class="even">
<td><code>people_fully_vaccinated_per_hundred</code></td>
<td>0.00</td>
<td>75.1</td>
<td>58.9</td>
<td>76.2</td>
<td>861</td>
</tr>
<tr class="odd">
<td><code>stringency_index</code></td>
<td>0</td>
<td>43.1</td>
<td>44.2</td>
<td>85.2</td>
<td>582</td>
</tr>
</tbody>
</table>
</section>
<section id="plots" class="level4">
<h4 class="anchored" data-anchor-id="plots">Plots</h4>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 397 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="proposal_website_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The distribution of daily COVID-19 deaths is right-skewed. Most observations correspond to relatively low numbers of deaths, while a small number of days experienced substantially higher mortality. This indicates considerable variation in COVID-19 mortality over time.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 397 rows containing missing values or values outside the scale range
(`geom_line()`).
Removed 397 rows containing missing values or values outside the scale range
(`geom_line()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="proposal_website_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Both COVID-19 cases and deaths exhibit clear wave-like patterns over time. Peaks in deaths generally occur shortly after peaks in reported cases, suggesting a temporal relationship between infection levels and mortality.</p>
<p><strong>Note:</strong>&nbsp;The number of daily deaths has been multiplied by a factor of 100 to make both time series visible on the same scale. This transformation is only for visualization purposes.</p>
</section>
<section id="data-quality-issues-and-planned-handling" class="level4">
<h4 class="anchored" data-anchor-id="data-quality-issues-and-planned-handling">Data quality issues and planned handling</h4>
<ul>
<li><p><strong>Substantial missingness in key variables.</strong> Vaccination variables have over 840 missing values, ICU counts 480, and the reproduction rate 637. These gaps are concentrated at the beginning of the period, before the corresponding indicators were collected. We will restrict each analysis to the time window in which the relevant variable is actually available rather than imputing early values.</p></li>
<li><p><strong><code>hosp_patients</code> is entirely missing for Germany (1,674 NAs).</strong> Although listed as a key variable in our earlier draft, it cannot be used. We will drop it and rely on <code>icu_patients</code> as the measure of hospital burden.</p></li>
<li><p><strong>Reporting spikes in raw counts.</strong> <code>new_cases</code> and <code>new_deaths</code> contain extreme single-day values (up to 1.59 M cases and 6,460 deaths) caused by delayed or batched reporting. We will use the smoothed 7-day-average variables throughout to reduce the influence of these artefacts.</p></li>
<li><p><strong>Suspicious ICU minimum.</strong> The minimum ICU value is exactly 100, which is more likely a lower bound or rounding artefact in the source than a true minimum. We will keep this in mind when interpreting small ICU values rather than treating it as a clean lowest observation</p></li>
</ul>
</section>
</section>
<section id="analysis-plan" class="level2">
<h2 class="anchored" data-anchor-id="analysis-plan"><strong>Analysis plan</strong></h2>
<p><strong>RQ1 — Vaccination coverage over time (descriptive).</strong> Variables: <code>date</code>, <code>people_fully_vaccinated_per_hundred</code>, <code>new_vaccinations_smoothed</code>. We will use a time-series line plot of <code>people_fully_vaccinated_per_hundred</code> to identify the overall phases of the vaccination campaign (start in early 2021, steep rise, plateau near 78 %), together with a line plot of <code>new_vaccinations_smoothed</code> to identify the period of peak vaccination activity, since the cumulative coverage variable is monotonic and cannot show a peak by itself. We will supplement both plots with descriptive statistics (e.g.&nbsp;range, mean, and timing of maximum daily vaccinations). Cleaning: filter each variable separately to the period where it is non-missing, since <code>people_fully_vaccinated_per_hundred</code> and <code>new_vaccinations_smoothed</code> may have different missingness patterns. Main risk: vaccination figures are not reported on every single day, so minor jumps or short gaps may be reporting artefacts rather than real changes in uptake.</p>
<p><strong>RQ2a — Vaccination vs.&nbsp;mortality (exploratory).</strong> Variables: <code>people_vaccinated_per_hundred</code>, <code>new_deaths_smoothed</code>, <code>date</code>. We will use line plots, scatterplots, correlation analysis, and descriptive statistics to examine whether higher vaccination coverage was associated with lower COVID-19 mortality in Germany. Cleaning: restrict to the period where vaccination data exist and use the smoothed death series to dampen reporting spikes identified earlier. Main risk: strong confounding by time — higher vaccination coverage coincides with new variants, seasonality, and relaxed restrictions (<code>stringency_index</code>). Since this is an exploratory analysis, we examine associations only and make no causal claims.</p>
<p><strong>RQ2b — Vaccination vs.&nbsp;ICU occupancy (exploratory).</strong> Variables: <code>people_vaccinated_per_hundred</code>, <code>icu_patients</code>, <code>date</code>. We will use the same approach as RQ2a (line plots, scatterplots, correlation analysis, descriptive statistics) to examine whether higher vaccination coverage was associated with lower ICU occupancy in Germany. Cleaning: same as RQ2a. Same time-confounding risk applies, plus the ICU lower-bound artefact (minimum value of exactly 100) noted in the quality checks, which we account for when interpreting low values. As an exploratory analysis, we make no causal claims.</p>
</section>
<section id="workflow-organisation" class="level2">
<h2 class="anchored" data-anchor-id="workflow-organisation">Workflow organisation</h2>
<ul>
<li><p><strong>Code style:</strong> We follow the tidyverse style guide and enforce it by formatting all code with <code>styler</code> before committing.</p></li>
<li><p><strong>Packages:</strong> <code>tidyverse</code> (including <code>readr</code>, <code>dplyr</code>, <code>ggplot2</code>)</p></li>
<li><p><strong>Git workflow:</strong> We collaborate via GitHub. Each of us works on their own feature branch, and changes are merged into <code>main</code> through pull requests with a short review. Where possible we split work by research question to minimise merge conflicts.</p></li>
<li><p><strong><code>.gitignore</code>:</strong> We exclude large raw data files, rendered Quarto output, and any <code>.env</code>/secret files to keep the repository lightweight and clean.</p></li>
</ul>
</section>
<section id="answering-the-research-questions" class="level2">
<h2 class="anchored" data-anchor-id="answering-the-research-questions">Answering the Research Questions</h2>
<section id="research-question-1" class="level3">
<h3 class="anchored" data-anchor-id="research-question-1">Research Question 1</h3>
<section id="model-specification-rq1" class="level4">
<h4 class="anchored" data-anchor-id="model-specification-rq1"><strong>Model specification — RQ1</strong></h4>
<ul>
<li><p><strong>Response:</strong> <code>people_fully_vaccinated_per_hundred</code></p></li>
<li><p><strong>Predictor:</strong> <code>date</code></p></li>
<li><p><strong>Filter:</strong> restricted to rows where <code>people_fully_vaccinated_per_hundred</code> is not missing (vaccination reporting only begins in early 2021)</p></li>
<li><p><strong>Method:</strong> <code>geom_line</code> (raw trajectory) plus a LOESS-smoothed trend line (<code>geom_smooth</code>) as a trial, to assess whether smoothing adds clarity over the raw reporting data</p></li>
<li><p><strong>Expected output:</strong> a time-series plot showing the trajectory of full vaccination coverage, from which we identify and qualitatively describe the main campaign phases (onset, steep rise, plateau near 78%)</p></li>
<li><p><strong>Interpretation:</strong> the plot characterizes how full vaccination coverage evolved over time; no comparison to other variables or causal claims are made at this stage</p></li>
</ul>
</section>
<section id="can-the-data-support-our-rq1-sanity-check" class="level4">
<h4 class="anchored" data-anchor-id="can-the-data-support-our-rq1-sanity-check">Can the data support our RQ1? – Sanity Check</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(covid_germany)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,674
Columns: 61
$ iso_code                                   &lt;chr&gt; "DEU", "DEU", "DEU", "DEU",…
$ continent                                  &lt;chr&gt; "Europe", "Europe", "Europe…
$ location                                   &lt;chr&gt; "Germany", "Germany", "Germ…
$ date                                       &lt;date&gt; 2020-01-05, 2020-01-06, 20…
$ total_cases                                &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ new_cases                                  &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, …
$ new_cases_smoothed                         &lt;dbl&gt; NA, NA, NA, NA, NA, 0.14, 0…
$ total_deaths                               &lt;dbl&gt; 3, 3, 3, 3, 3, 3, 3, 3, 3, …
$ new_deaths                                 &lt;dbl&gt; 3, 0, 0, 0, 0, 0, 0, 0, 0, …
$ new_deaths_smoothed                        &lt;dbl&gt; NA, NA, NA, NA, NA, 0.43, 0…
$ total_cases_per_million                    &lt;dbl&gt; 0.01, 0.01, 0.01, 0.01, 0.0…
$ new_cases_per_million                      &lt;dbl&gt; 0.01, 0.00, 0.00, 0.00, 0.0…
$ new_cases_smoothed_per_million             &lt;dbl&gt; NA, NA, NA, NA, NA, 0, 0, 0…
$ total_deaths_per_million                   &lt;dbl&gt; 0.04, 0.04, 0.04, 0.04, 0.0…
$ new_deaths_per_million                     &lt;dbl&gt; 0.04, 0.00, 0.00, 0.00, 0.0…
$ new_deaths_smoothed_per_million            &lt;dbl&gt; NA, NA, NA, NA, NA, 0, 0, 0…
$ reproduction_rate                          &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ icu_patients                               &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ icu_patients_per_million                   &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ weekly_icu_admissions                      &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ weekly_icu_admissions_per_million          &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ weekly_hosp_admissions                     &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ weekly_hosp_admissions_per_million         &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ total_tests                                &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ total_tests_per_thousand                   &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ new_tests_smoothed                         &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ new_tests_smoothed_per_thousand            &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ positive_rate                              &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ tests_per_case                             &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ tests_units                                &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA,…
$ total_vaccinations                         &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ people_vaccinated                          &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ people_fully_vaccinated                    &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ total_boosters                             &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ new_vaccinations                           &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ new_vaccinations_smoothed                  &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ total_vaccinations_per_hundred             &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ people_vaccinated_per_hundred              &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ people_fully_vaccinated_per_hundred        &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ total_boosters_per_hundred                 &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ new_vaccinations_smoothed_per_million      &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ new_people_vaccinated_smoothed             &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ new_people_vaccinated_smoothed_per_hundred &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA,…
$ stringency_index                           &lt;dbl&gt; 0.00, 0.00, 0.00, 0.00, 0.0…
$ population_density                         &lt;dbl&gt; 237.02, 237.02, 237.02, 237…
$ median_age                                 &lt;dbl&gt; 46.6, 46.6, 46.6, 46.6, 46.…
$ aged_65_older                              &lt;dbl&gt; 21.45, 21.45, 21.45, 21.45,…
$ aged_70_older                              &lt;dbl&gt; 15.96, 15.96, 15.96, 15.96,…
$ gdp_per_capita                             &lt;dbl&gt; 45229.24, 45229.24, 45229.2…
$ cardiovasc_death_rate                      &lt;dbl&gt; 156.14, 156.14, 156.14, 156…
$ diabetes_prevalence                        &lt;dbl&gt; 8.31, 8.31, 8.31, 8.31, 8.3…
$ female_smokers                             &lt;dbl&gt; 28.2, 28.2, 28.2, 28.2, 28.…
$ male_smokers                               &lt;dbl&gt; 33.1, 33.1, 33.1, 33.1, 33.…
$ hospital_beds_per_thousand                 &lt;dbl&gt; 8, 8, 8, 8, 8, 8, 8, 8, 8, …
$ life_expectancy                            &lt;dbl&gt; 81.33, 81.33, 81.33, 81.33,…
$ human_development_index                    &lt;dbl&gt; 0.95, 0.95, 0.95, 0.95, 0.9…
$ population                                 &lt;dbl&gt; 83369840, 83369840, 8336984…
$ excess_mortality_cumulative_absolute       &lt;dbl&gt; -760.7, NA, NA, NA, NA, NA,…
$ excess_mortality_cumulative                &lt;dbl&gt; -3.87, NA, NA, NA, NA, NA, …
$ excess_mortality                           &lt;dbl&gt; -3.87, NA, NA, NA, NA, NA, …
$ excess_mortality_cumulative_per_million    &lt;dbl&gt; -9.13, NA, NA, NA, NA, NA, …</code></pre>
</div>
</div>
<p>We confirmed that <code>date</code>, <code>people_fully_vaccinated_per_hundred</code> and <code>new_vaccinations_smoothed</code>have the correct data types in order for us to create the planned line plot (Date and double) using glimpse().</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#check variable people_fully_vaccinated_per_hundred</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>covid_germany <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(people_fully_vaccinated_per_hundred)) <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">start =</span> <span class="fu">min</span>(date), <span class="at">end =</span> <span class="fu">max</span>(date))</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>covid_germany <span class="sc">%&gt;%</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(people_fully_vaccinated_per_hundred)) <span class="sc">%&gt;%</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(date) <span class="sc">%&gt;%</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gap =</span> <span class="fu">as.numeric</span>(date <span class="sc">-</span> <span class="fu">lag</span>(date))) <span class="sc">%&gt;%</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">max_gap =</span> <span class="fu">max</span>(gap, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The Data coverage on vaccination stars in January of 2021 and ends in July of 2023. In this time range the data coverage is very good with a maximum gap of 1 day without coverage.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#check variable new_vaccinations_smoothed</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>covid_germany <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(new_vaccinations_smoothed)) <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">start =</span> <span class="fu">min</span>(date), <span class="at">end =</span> <span class="fu">max</span>(date))</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>covid_germany <span class="sc">%&gt;%</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(new_vaccinations_smoothed)) <span class="sc">%&gt;%</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(date) <span class="sc">%&gt;%</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gap =</span> <span class="fu">as.numeric</span>(date <span class="sc">-</span> <span class="fu">lag</span>(date))) <span class="sc">%&gt;%</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">max_gap =</span> <span class="fu">max</span>(gap, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>By using the same method as before we now found out that the data for <code>new_vaccinations_smoothed</code>ranges from December 2020 until July 2023 datewise. Also just like with <code>people_fully_vaccinated_per_hundred</code> the coverage for this variable is very good.</p>
<p>As we explored in the <em>Domain-informed quality checks</em> part of our Proposal, the values of <code>people_fully_vaccinated_per_hundred</code> ranges from 0 to 78, which is enough variation to detect distinct phases over the available period.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>covid_germany <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(new_vaccinations_smoothed)) <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">min =</span> <span class="fu">min</span>(new_vaccinations_smoothed),</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">max =</span> <span class="fu">max</span>(new_vaccinations_smoothed),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(new_vaccinations_smoothed),</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">sd</span>(new_vaccinations_smoothed)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The variation of values as well as the variance of <code>new_vaccinations_smoothed</code> is also going to be sufficient to answer our research question.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>